#File: Makefile
#Purpose: Compile Programs
#Author: Debi Majumdar

CC = clang
CFLAGS =  -Werror -Wall -Wextra -Wconversion -Wdouble-promotion -Wstrict-prototypes -pedantic






.PHONY: all



.PHONY: clean
